//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IN2U.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IN2UEntities : DbContext
    {
        public IN2UEntities()
            : base("name=IN2UEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VwHS_Contacts> VwHS_Contacts { get; set; }
        public virtual DbSet<ReferrerInfo> ReferrerInfoes { get; set; }
        public virtual DbSet<WorkerInfo> WorkerInfoes { get; set; }
    }
}
