//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IN2U.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwHS_Contacts
    {
        public int ContactID { get; set; }
        public int Vid { get; set; }
        public string UserType { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string CreateDate { get; set; }
        public string LastModifiedDate { get; set; }
    }
}
